# Generated by Django 4.2.6 on 2023-10-31 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classviewshome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=340, verbose_name='Описание')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classviewshome.article', verbose_name='Статья')),
            ],
        ),
    ]
